/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.renteasy.views.admin;

public class FrmGestionFotos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionFotos.class.getName());

    /**
     * Creates new form FrmGestionFotos
     */
    public FrmGestionFotos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTituloPropiedad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFotos = new javax.swing.JList<>();
        btnSubirFoto = new javax.swing.JButton();
        btnEliminarFoto = new javax.swing.JButton();
        btnVistaPrevia = new javax.swing.JButton();
        btnEstablecerPrincipal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblImagenPrevia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInfoFoto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalFotos = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Gestión de Fotos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 40));

        lblTituloPropiedad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTituloPropiedad.setForeground(new java.awt.Color(52, 73, 94));
        lblTituloPropiedad.setText("Propiedad: Cargando...");
        jPanel1.add(lblTituloPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 400, 25));

        listFotos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listFotos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cargando fotos..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listFotos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listFotos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 340, 250));

        btnSubirFoto.setBackground(new java.awt.Color(46, 204, 113));
        btnSubirFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubirFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnSubirFoto.setText("Subir Foto");
        btnSubirFoto.setBorder(null);
        btnSubirFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSubirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, 35));

        btnEliminarFoto.setBackground(new java.awt.Color(231, 76, 60));
        btnEliminarFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFoto.setText("Eliminar");
        btnEliminarFoto.setBorder(null);
        btnEliminarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, 35));

        btnVistaPrevia.setBackground(new java.awt.Color(52, 152, 219));
        btnVistaPrevia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVistaPrevia.setForeground(new java.awt.Color(255, 255, 255));
        btnVistaPrevia.setText("Vista Previa");
        btnVistaPrevia.setBorder(null);
        btnVistaPrevia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVistaPrevia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 100, 35));

        btnEstablecerPrincipal.setBackground(new java.awt.Color(142, 68, 173));
        btnEstablecerPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEstablecerPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnEstablecerPrincipal.setText("Foto Principal");
        btnEstablecerPrincipal.setBorder(null);
        btnEstablecerPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEstablecerPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 130, 35));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vista Previa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenPrevia.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenPrevia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenPrevia.setText("Seleccione una foto para ver la vista previa");
        lblImagenPrevia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagenPrevia.setOpaque(true);
        jPanel2.add(lblImagenPrevia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 200));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtInfoFoto.setColumns(20);
        txtInfoFoto.setLineWrap(true);
        txtInfoFoto.setRows(3);
        txtInfoFoto.setText("Información de la foto seleccionada aparecerá aquí...");
        txtInfoFoto.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtInfoFoto);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 70));

        jLabel3.setText("Información:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 320, 350));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 690, 10));

        lblTotalFotos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalFotos.setForeground(new java.awt.Color(52, 73, 94));
        lblTotalFotos.setText("Total de fotos: 0");
        jPanel1.add(lblTotalFotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, 25));

        btnVolver.setBackground(new java.awt.Color(95, 106, 106));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 80, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionFotos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarFoto;
    public javax.swing.JButton btnEstablecerPrincipal;
    public javax.swing.JButton btnSubirFoto;
    public javax.swing.JButton btnVistaPrevia;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblImagenPrevia;
    public javax.swing.JLabel lblTituloPropiedad;
    public javax.swing.JLabel lblTotalFotos;
    public javax.swing.JList<String> listFotos;
    public javax.swing.JTextArea txtInfoFoto;
    // End of variables declaration//GEN-END:variables
}

