/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.renteasy.views.admin;

public class FrmSoporte extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSoporte.class.getName());

    /**
     * Creates new form FrmSoporte
     */
    public FrmSoporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMensajes = new javax.swing.JTable();
        btnNuevoMensaje = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        btnResponder = new javax.swing.JButton();
        btnCerrarTicket = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbEstadoFiltro = new javax.swing.JComboBox<>();
        btnRefrescar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAsuntoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiarFiltros = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtUsuarioBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalMensajes = new javax.swing.JLabel();
        lblMensajesAbiertos = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Centro de Soporte Técnico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 350, 40));

        tblMensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Asunto", "Estado", "Fecha Creación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMensajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblMensajes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 940, 320));

        btnNuevoMensaje.setBackground(new java.awt.Color(46, 204, 113));
        btnNuevoMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoMensaje.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoMensaje.setText("Nuevo Ticket");
        btnNuevoMensaje.setBorder(null);
        btnNuevoMensaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnNuevoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 120, 35));

        btnVerDetalle.setBackground(new java.awt.Color(52, 152, 219));
        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setBorder(null);
        btnVerDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 110, 35));

        btnResponder.setBackground(new java.awt.Color(142, 68, 173));
        btnResponder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResponder.setForeground(new java.awt.Color(255, 255, 255));
        btnResponder.setText("Responder");
        btnResponder.setBorder(null);
        btnResponder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnResponder, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 110, 35));

        btnCerrarTicket.setBackground(new java.awt.Color(230, 126, 34));
        btnCerrarTicket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarTicket.setText("Cerrar Ticket");
        btnCerrarTicket.setBorder(null);
        btnCerrarTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnCerrarTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 120, 35));

        btnEliminar.setBackground(new java.awt.Color(231, 76, 60));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 100, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Estado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 25));

        cmbEstadoFiltro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEstadoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "abierto", "en_proceso", "cerrado" }));
        jPanel1.add(cmbEstadoFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 25));

        btnRefrescar.setBackground(new java.awt.Color(155, 89, 182));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.setBorder(null);
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 80, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros de Búsqueda"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Asunto:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 50, 25));
        jPanel2.add(txtAsuntoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, 150, 25));

        btnBuscar.setBackground(new java.awt.Color(41, 128, 185));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 25, 60, 25));

        btnLimpiarFiltros.setBackground(new java.awt.Color(149, 165, 166));
        btnLimpiarFiltros.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnLimpiarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFiltros.setText("Limpiar");
        btnLimpiarFiltros.setBorder(null);
        btnLimpiarFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnLimpiarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 25, 60, 25));

        jLabel4.setText("Usuario:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 25));
        jPanel2.add(txtUsuarioBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, 25));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 470, 95));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 940, 10));

        lblTotalMensajes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalMensajes.setForeground(new java.awt.Color(52, 73, 94));
        lblTotalMensajes.setText("Total de tickets: 0");
        jPanel1.add(lblTotalMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 150, 25));

        lblMensajesAbiertos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensajesAbiertos.setForeground(new java.awt.Color(231, 76, 60));
        lblMensajesAbiertos.setText("Abiertos: 0");
        jPanel1.add(lblMensajesAbiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 100, 25));

        btnVolver.setBackground(new java.awt.Color(95, 106, 106));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 80, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSoporte().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCerrarTicket;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiarFiltros;
    public javax.swing.JButton btnNuevoMensaje;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnResponder;
    public javax.swing.JButton btnVerDetalle;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cmbEstadoFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblMensajesAbiertos;
    public javax.swing.JLabel lblTotalMensajes;
    public javax.swing.JTable tblMensajes;
    public javax.swing.JTextField txtAsuntoBuscar;
    public javax.swing.JTextField txtUsuarioBuscar;
    // End of variables declaration//GEN-END:variables
}

