/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.renteasy.views.propietario;

public class FrmGestionDeSolicitudesPropietario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionDeSolicitudesPropietario.class.getName());

    /**
     * Creates new form FrmGestionDeSolicitudesPropietario
     */
    public FrmGestionDeSolicitudesPropietario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        btnVerDetalle = new javax.swing.JButton();
        btnAceptarSolicitud = new javax.swing.JButton();
        btnRechazarSolicitud = new javax.swing.JButton();
        btnEliminarSolicitud = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbEstadoSolicitud = new javax.swing.JComboBox<>();
        btnRefrescar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPropiedadBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiarFiltros = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtInquilinoBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalSolicitudes = new javax.swing.JLabel();
        lblSolicitudesPendientes = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Solicitudes de Alquiler - RentEasy");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Gestión de Solicitudes de Alquiler");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 40));

        tblSolicitudes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inquilino", "Propiedad", "Mensaje", "Estado", "Fecha Solicitud"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSolicitudes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblSolicitudes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 940, 320));

        btnVerDetalle.setBackground(new java.awt.Color(52, 152, 219));
        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setBorder(null);
        btnVerDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 110, 35));

        btnAceptarSolicitud.setBackground(new java.awt.Color(39, 174, 96));
        btnAceptarSolicitud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptarSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarSolicitud.setText("Aceptar");
        btnAceptarSolicitud.setBorder(null);
        btnAceptarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAceptarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 100, 35));

        btnRechazarSolicitud.setBackground(new java.awt.Color(230, 126, 34));
        btnRechazarSolicitud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRechazarSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        btnRechazarSolicitud.setText("Rechazar");
        btnRechazarSolicitud.setBorder(null);
        btnRechazarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRechazarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 100, 35));

        btnEliminarSolicitud.setBackground(new java.awt.Color(231, 76, 60));
        btnEliminarSolicitud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSolicitud.setText("Eliminar");
        btnEliminarSolicitud.setBorder(null);
        btnEliminarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 100, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Estado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 25));

        cmbEstadoSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEstadoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "pendiente", "aceptada", "rechazada" }));
        jPanel1.add(cmbEstadoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 25));

        btnRefrescar.setBackground(new java.awt.Color(155, 89, 182));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.setBorder(null);
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 80, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros de Búsqueda"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Propiedad:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 70, 25));
        jPanel2.add(txtPropiedadBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 25, 150, 25));

        btnBuscar.setBackground(new java.awt.Color(41, 128, 185));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 25, 60, 25));

        btnLimpiarFiltros.setBackground(new java.awt.Color(149, 165, 166));
        btnLimpiarFiltros.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnLimpiarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFiltros.setText("Limpiar");
        btnLimpiarFiltros.setBorder(null);
        btnLimpiarFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnLimpiarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 25, 60, 25));

        jLabel4.setText("Inquilino:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 25));
        jPanel2.add(txtInquilinoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 150, 25));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 470, 95));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 940, 10));

        lblTotalSolicitudes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalSolicitudes.setForeground(new java.awt.Color(52, 73, 94));
        lblTotalSolicitudes.setText("Total de solicitudes: 0");
        jPanel1.add(lblTotalSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 200, 25));

        lblSolicitudesPendientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSolicitudesPendientes.setForeground(new java.awt.Color(230, 126, 34));
        lblSolicitudesPendientes.setText("Pendientes: 0");
        jPanel1.add(lblSolicitudesPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 150, 25));

        btnVolver.setBackground(new java.awt.Color(95, 106, 106));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 80, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionDeSolicitudesPropietario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarSolicitud;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminarSolicitud;
    public javax.swing.JButton btnLimpiarFiltros;
    public javax.swing.JButton btnRechazarSolicitud;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnVerDetalle;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cmbEstadoSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblSolicitudesPendientes;
    public javax.swing.JLabel lblTotalSolicitudes;
    public javax.swing.JTable tblSolicitudes;
    public javax.swing.JTextField txtInquilinoBuscar;
    public javax.swing.JTextField txtPropiedadBuscar;
    // End of variables declaration//GEN-END:variables
}

