/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.renteasy.views.propietario;

public class FrmGestionDePagosPropietario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionDePagosPropietario.class.getName());

    /**
     * Creates new form FrmGestionDePagosPropietario
     */
    public FrmGestionDePagosPropietario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        btnNuevoPago = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        btnMarcarPagado = new javax.swing.JButton();
        btnEliminarPago = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbEstadoPago = new javax.swing.JComboBox<>();
        btnRefrescar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtContratoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiarFiltros = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFechaDesde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaHasta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalPagos = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Gestión de Pagos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 40));

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contrato", "Propiedad", "Inquilino", "Fecha Pago", "Monto", "Método", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPagos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblPagos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 940, 320));

        btnNuevoPago.setBackground(new java.awt.Color(46, 204, 113));
        btnNuevoPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoPago.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoPago.setText("Nuevo Pago");
        btnNuevoPago.setBorder(null);
        btnNuevoPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnNuevoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 120, 35));

        btnVerDetalle.setBackground(new java.awt.Color(52, 152, 219));
        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setBorder(null);
        btnVerDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 110, 35));

        btnMarcarPagado.setBackground(new java.awt.Color(39, 174, 96));
        btnMarcarPagado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarPagado.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarPagado.setText("Marcar Pagado");
        btnMarcarPagado.setBorder(null);
        btnMarcarPagado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnMarcarPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 130, 35));

        btnEliminarPago.setBackground(new java.awt.Color(231, 76, 60));
        btnEliminarPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPago.setText("Eliminar");
        btnEliminarPago.setBorder(null);
        btnEliminarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 100, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Estado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 25));

        cmbEstadoPago.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEstadoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "pendiente", "pagado", "vencido" }));
        jPanel1.add(cmbEstadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 25));

        btnRefrescar.setBackground(new java.awt.Color(155, 89, 182));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.setBorder(null);
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 80, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros de Búsqueda"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Contrato:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 60, 25));
        jPanel2.add(txtContratoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, 150, 25));

        btnBuscar.setBackground(new java.awt.Color(41, 128, 185));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 25, 60, 25));

        btnLimpiarFiltros.setBackground(new java.awt.Color(149, 165, 166));
        btnLimpiarFiltros.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnLimpiarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFiltros.setText("Limpiar");
        btnLimpiarFiltros.setBorder(null);
        btnLimpiarFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnLimpiarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 25, 60, 25));

        jLabel4.setText("Desde:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 25));

        txtFechaDesde.setText("YYYY-MM-DD");
        jPanel2.add(txtFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, 25));

        jLabel5.setText("Hasta:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 50, 25));

        txtFechaHasta.setText("YYYY-MM-DD");
        jPanel2.add(txtFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 25));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 380, 95));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 940, 10));

        lblTotalPagos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPagos.setForeground(new java.awt.Color(52, 73, 94));
        lblTotalPagos.setText("Total de pagos: 0");
        jPanel1.add(lblTotalPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 150, 25));

        lblMontoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMontoTotal.setForeground(new java.awt.Color(39, 174, 96));
        lblMontoTotal.setText("Monto total: $0.00");
        jPanel1.add(lblMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 200, 25));

        btnVolver.setBackground(new java.awt.Color(95, 106, 106));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 80, 35));

        btnGenerarReporte.setBackground(new java.awt.Color(142, 68, 173));
        btnGenerarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.setBorder(null);
        btnGenerarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 130, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionDePagosPropietario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminarPago;
    public javax.swing.JButton btnGenerarReporte;
    public javax.swing.JButton btnLimpiarFiltros;
    public javax.swing.JButton btnMarcarPagado;
    public javax.swing.JButton btnNuevoPago;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnVerDetalle;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cmbEstadoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblMontoTotal;
    public javax.swing.JLabel lblTotalPagos;
    public javax.swing.JTable tblPagos;
    public javax.swing.JTextField txtContratoBuscar;
    public javax.swing.JTextField txtFechaDesde;
    public javax.swing.JTextField txtFechaHasta;
    // End of variables declaration//GEN-END:variables
}

