/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.renteasy.views.inquilino;

public class FrmGestionDeSolicitudesUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionDeSolicitudesUsuario.class.getName());

    /**
     * Creates new form FrmGestionDeSolicitudesUsuario
     */
    public FrmGestionDeSolicitudesUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        btnVerDetalle = new javax.swing.JButton();
        btnEliminarSolicitud = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbEstadoSolicitud = new javax.swing.JComboBox<>();
        btnRefrescar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalSolicitudes = new javax.swing.JLabel();
        lblSolicitudesRechazada = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblSolicitudesAceptada = new javax.swing.JLabel();
        lblSolicitudesPendiente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Solicitudes - RentEasy");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Gestión de Solicitudes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 40));

        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Inquilino", "Propiedad", "Mensaje", "Estado", "Fecha Solicitud"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSolicitudes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblSolicitudes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 940, 320));

        btnVerDetalle.setBackground(new java.awt.Color(52, 152, 219));
        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setBorder(null);
        btnVerDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 110, 35));

        btnEliminarSolicitud.setBackground(new java.awt.Color(231, 76, 60));
        btnEliminarSolicitud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSolicitud.setText("Eliminar");
        btnEliminarSolicitud.setBorder(null);
        btnEliminarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 100, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Estado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 25));

        cmbEstadoSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEstadoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "pendiente", "aceptada", "rechazada" }));
        jPanel1.add(cmbEstadoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 25));

        btnRefrescar.setBackground(new java.awt.Color(155, 89, 182));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.setBorder(null);
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 80, 25));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 940, 10));

        lblTotalSolicitudes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalSolicitudes.setForeground(new java.awt.Color(52, 73, 94));
        lblTotalSolicitudes.setText("Total de solicitudes: 0");
        jPanel1.add(lblTotalSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 200, 25));

        lblSolicitudesRechazada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSolicitudesRechazada.setForeground(new java.awt.Color(231, 76, 60));
        lblSolicitudesRechazada.setText("Rechazada: 0");
        jPanel1.add(lblSolicitudesRechazada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 150, 25));

        btnVolver.setBackground(new java.awt.Color(95, 106, 106));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 80, 35));

        lblSolicitudesAceptada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSolicitudesAceptada.setForeground(new java.awt.Color(0, 153, 0));
        lblSolicitudesAceptada.setText("Aceptadas: 0");
        jPanel1.add(lblSolicitudesAceptada, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 150, 25));

        lblSolicitudesPendiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSolicitudesPendiente.setForeground(new java.awt.Color(230, 126, 34));
        lblSolicitudesPendiente.setText("Pendientes: 0");
        jPanel1.add(lblSolicitudesPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 150, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionDeSolicitudesUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarSolicitud;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnVerDetalle;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cmbEstadoSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblSolicitudesAceptada;
    public javax.swing.JLabel lblSolicitudesPendiente;
    public javax.swing.JLabel lblSolicitudesRechazada;
    public javax.swing.JLabel lblTotalSolicitudes;
    public javax.swing.JTable tblSolicitudes;
    // End of variables declaration//GEN-END:variables
}

